#pragma once
#include <stdint.h>
#include "curve.h"

// Controller tunables (firmware-only). Pure constants — logic lives in
// curve.h / control_math.h.

static const int16_t  DEADZONE_RAW = 80;     // raw counts ignored about center
static const int32_t  HALF_RANGE   = 2000;   // raw counts from center to full deflection
static const uint8_t  SPEED_STEP   = 10;     // speed % increment per button press
static const uint32_t SEND_INTERVAL_MS = 20; // ~50Hz send rate

// Stick response curve (config generated by docs/curve-visualizer.html).
static const CurveCfg CURVE = { 3, 1.0f, 0.05f, 6.0f, 0.59f, 2.0f };  // logistic
