#pragma once
#include <stdint.h>
#include "curve.h"

// Controller tunables (firmware-only). Pure constants — logic lives in
// curve.h / control_math.h.

static const int16_t  DEADZONE_RAW = 80;     // raw counts ignored about center
static const int32_t  HALF_RANGE   = 2000;   // raw counts from center to full deflection
static const uint8_t  SPEED_STEP   = 10;     // speed % increment per button press
static const uint32_t SEND_INTERVAL_MS = 20; // ~50Hz send rate

// Axis inversion toggles. Flip per-axis if joystick orientation is reversed
// relative to robot frame (e.g. controller mounted backwards).
static const bool INVERT_VX    = true;   // front <-> back
static const bool INVERT_VY    = true;   // strafe left <-> right
static const bool INVERT_OMEGA = false;  // CW <-> CCW

// Stick response curve (config generated by docs/curve-visualizer.html).
static const CurveCfg CURVE = { 3, 1.0f, 0.05f, 6.0f, 0.59f, 2.0f };  // logistic (vx/vy)

// Turn-axis curve (BUG-010/011). The shared logistic CURVE crushes small inputs
// ~60x — applied to omega it makes a "slight turn" produce near-zero commanded
// yaw, so curving and spinning are not a smooth function of stick (the operator's
// small turn does nothing, then the cart snaps). omega gets its own gentler curve:
// a mild power (p=1.4) with NO curve-side deadzone (normalize() already deadbands
// the raw stick, so the logistic's extra 0.05 deadzone was a redundant second dead
// region on the turn axis). vx/vy keep CURVE so working forward/strafe feel is
// unchanged.
static const CurveCfg CURVE_OMEGA = { 4, 1.0f, 0.0f, 0.0f, 0.0f, 1.3f };  // power, responsive

// Forward (vx) is summed from BOTH stick verticals (either stick drives forward).
// The right stick therefore drives vx (its vertical) AND omega (its horizontal),
// so a diagonal right-stick turn gesture perturbs forward speed (BUG-011). Set
// false to make vx come from the LEFT stick only (right stick = pure turn), at the
// cost of losing right-stick forward. Default true preserves the dual-stick scheme.
#ifndef VX_FROM_BOTH_STICKS
#define VX_FROM_BOTH_STICKS 1
#endif
