#pragma once
#include <math.h>
#include <stdint.h>

// Stick response curve (config generated by docs/curve-visualizer.html).
// Logic-only/host-safe (<math.h> for expf/powf/fabsf). The curve coefficients
// live in config_controller.h as a CurveCfg instance; applyCurve takes it by ref.
struct CurveCfg { int kind; float max; float deadzone; float k; float mid; float p; };

// stick in [-1000..+1000]; returns shaped output in [-max..+max].
static inline float applyCurve(int16_t stick, const CurveCfg& cfg) {
  if (stick == 0) return 0.0f;
  float sign = (stick < 0) ? -1.0f : 1.0f;
  float x = fabsf((float)stick) / 1000.0f;
  if (x <= cfg.deadzone) return 0.0f;
  float t = (x - cfg.deadzone) / (1.0f - cfg.deadzone);
  if (t > 1.0f) t = 1.0f;
  float y;
  switch (cfg.kind) {
    case 0: y = t; break;
    case 1: y = t * t * (3.0f - 2.0f * t); break;
    case 2: y = t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f); break;
    case 3: {
      float s0 = 1.0f / (1.0f + expf(-cfg.k * (0.0f - cfg.mid)));
      float s1 = 1.0f / (1.0f + expf(-cfg.k * (1.0f - cfg.mid)));
      float st = 1.0f / (1.0f + expf(-cfg.k * (t - cfg.mid)));
      y = (st - s0) / (s1 - s0);
      break;
    }
    case 4: y = powf(t, cfg.p); break;
    default: y = t;
  }
  return sign * y * cfg.max;
}
